In [1]:
import numpy as np

In [2]:
a = np.random.randn(5)

In [3]:
a

array([ 1.18518847,  0.00208449,  0.24247508,  0.78875035, -1.32463607])

In [4]:
np.sum(a)

0.893862327311213

In [5]:
a.shape

(5,)

In [6]:
b = np.random.randn(5,3)

In [7]:
b

array([[-0.59257289, -1.23238827, -1.09098572],
       [ 1.91048028,  1.25666196,  0.2081481 ],
       [ 1.40201169,  0.94997061,  1.10962072],
       [ 1.17402457, -0.69703926,  1.58526913],
       [ 0.13095652,  0.70891141, -0.07457314]])

In [10]:
a.reshape(5,1)

array([[ 1.18518847],
       [ 0.00208449],
       [ 0.24247508],
       [ 0.78875035],
       [-1.32463607]])

In [12]:
a.reshape(5,1)+b

array([[ 0.59261559, -0.0471998 ,  0.09420276],
       [ 1.91256478,  1.25874646,  0.21023259],
       [ 1.64448677,  1.19244569,  1.3520958 ],
       [ 1.96277492,  0.09171109,  2.37401948],
       [-1.19367954, -0.61572466, -1.39920921]])

In [13]:
a.T

array([ 1.18518847,  0.00208449,  0.24247508,  0.78875035, -1.32463607])

In [14]:
print(b)

[[-0.59257289 -1.23238827 -1.09098572]
 [ 1.91048028  1.25666196  0.2081481 ]
 [ 1.40201169  0.94997061  1.10962072]
 [ 1.17402457 -0.69703926  1.58526913]
 [ 0.13095652  0.70891141 -0.07457314]]


In [15]:
b

array([[-0.59257289, -1.23238827, -1.09098572],
       [ 1.91048028,  1.25666196,  0.2081481 ],
       [ 1.40201169,  0.94997061,  1.10962072],
       [ 1.17402457, -0.69703926,  1.58526913],
       [ 0.13095652,  0.70891141, -0.07457314]])

In [19]:
assert(b.shape == (5,3))